version: '3'
services:
  app:
    stdin_open: true 
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    command: /bin/sh -c "pnpm install && pnpm dev"
