version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    expose:
      - 3000
    ports:
      - 3000:3000
    command: /bin/sh -c "pnpm install && pnpm dev"
